name: DevOps

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Docker setup BuildX
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Github Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

      - name: Build and push to Github Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/wsskorea-ict/slack-bot-lambda:${{ steps.vars.outputs.tag }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: x64

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Build function using SAM
        run: sam build

      - name: Package function using SAM
        run: |
          sam package \
            --template-file package.yml \
            --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
            --s3-prefix slack-bot-lambda

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: package.yml

  deploy:
    needs: build

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy function using SAM
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --template-file package.yml
            --stack-name slack-bot-lambda \
            --parameter-overrides \
              LambdaFunctionExecutionRoleArn=${{ secrets.AWS_LAMBDA_FUNCTION_EXECUTION_ROLE_ARN }} \
              SlackIncomingWebhookUrl=${{ secrets.SLACK_INCOMING_WEBHOOK_URL }} \
              KmsKeyArn=${{ secrets.AWS_KMS_KEY_ARN }} \
              SqsArn=${{ secrets.AWS_SQS_ARN }} \
            --tags Project=Mail